name: flutter_mock_app
description: "FlutterMockApp — standalone Flutter prototype designed for local testing and feature validation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State management
  provider: ^6.1.2
  # Declarative routing
  go_router: ^14.6.2
  flutter_animate: ^4.5.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
