name: flutter_mock_app
description: FlutterMockApp prototype — Firebase + Terraform + Fastlane delivery pipeline.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
